# enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y

# enable RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# set underglow behavior to solid
# CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0

# turn off RGB underglow when keyboard goes into idle state
# CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# Hue step in degrees (0-359) used by RGB actions default 10
# CONFIG_ZMK_RGB_UNDERGLOW_HUE_STEP=30

# Brightness step in percent used by RGB actions default 10
# CONFIG_ZMK_RGB_UNDERGLOW_SAT_STEP=2
# CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=10
# CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=240
# CONFIG_ZMK_RGB_UNDERGLOW_HUE_STEP=5
# CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=10
# CONFIG_ZMK_RGB_UNDERGLOW_SAT_STEP=2
# CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=5
# CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=15

# disable external power toggling by the underglow toggle
# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
