name: Build with Custom Display

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      board: '["mikoto@7.2"]'
      shield: '["corne_left nice_view_adapter custom_display", "corne_right nice_view_adapter custom_display"]'
      modules: '["default"]'
      kconfig: '["default"]'